In [1]:
import numpy as np


In [2]:
import genetic_algorithm
import generation_parameters
import selection_parameters
import crossover_parameters
import mutation_parameters
import algorithm_parameters
import genetic_algorithm_parameters

import test_all_ones_problem
import test_feature_selection_problem

In [3]:
test_problem = test_all_ones_problem.AllOnesProblem(dimension=100)

generation_params = generation_parameters.GenerationParameters(generation_type='uniform')
selection_params = selection_parameters.SelectionParameters(selection_type='tournament', tournament_size=2)
crossover_params = crossover_parameters.CrossoverParameters(crossover_type='uniform')
mutation_params = mutation_parameters.MutationParameters(mutation_type='standard', mutation_probability=0.01)

algorithm_params = algorithm_parameters.MainAlgorithmParameters(population_size=100, 
                                                                generations_number=500, 
                                                                dimension=100)

ga_algorithm_params = genetic_algorithm_parameters.GeneticAlgorithmParameters(
    algorithm=algorithm_params,
    generation=generation_params,
    selection=selection_params,
    crossover=crossover_params,
    mutation=mutation_params
)


In [73]:
ga = genetic_algorithm.GeneticAlgorithm(parameters=ga_algorithm_params, problem=test_problem)

In [74]:
ga.generate()

In [75]:
ga._parameters.algorithm.size

100

In [76]:
ga.population

array([[0, 0, 1, ..., 1, 1, 1],
       [0, 0, 1, ..., 1, 1, 0],
       [0, 1, 1, ..., 1, 0, 0],
       ...,
       [0, 1, 1, ..., 1, 1, 0],
       [0, 0, 1, ..., 1, 1, 0],
       [1, 0, 1, ..., 0, 0, 0]])

In [77]:
ga.fitness

array([53, 42, 52, 48, 44, 50, 55, 40, 54, 59, 51, 46, 49, 55, 50, 56, 49,
       47, 58, 50, 59, 48, 39, 49, 47, 45, 48, 49, 45, 46, 63, 52, 47, 48,
       55, 50, 63, 60, 52, 57, 58, 46, 63, 54, 45, 52, 52, 52, 43, 58, 41,
       49, 50, 53, 46, 53, 47, 51, 45, 53, 45, 53, 48, 52, 54, 46, 46, 38,
       50, 56, 50, 52, 42, 51, 52, 42, 51, 50, 56, 56, 54, 51, 47, 47, 49,
       52, 40, 49, 51, 51, 50, 56, 54, 58, 47, 56, 49, 59, 41, 55])

In [78]:
ga.perform_select()

(99, 19)

In [79]:
offsp = ga.perform_crossover(92, 39)
offsp

array([1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0])

In [80]:
ga.perform_mutation(offsp)

array([1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0], dtype=int32)

In [81]:
indices_to_mutate = np.random.choice(2, ga._parameters.algorithm.dimension,
                                              p=[0.9, 0.1])
indices_to_mutate.sum()

9

In [82]:
ga.perform_next()

In [86]:
ga.run()

In [87]:
ga.best_value

94.0

In [91]:
test = np.array([[0,1,2], [3,4,5]])

In [4]:
feature_selection_problem = test_feature_selection_problem.Problem(10)
feature_selection_problem.set_data('C:\\Users\\ivanry\\Documents\\Repositories\\models-and-learning\\TestApp\\TestApp\\kihd_100.xlsx')


In [11]:
test = feature_selection_problem.evaluate(np.random.randint(2, size=[5, 100]))


C:\Users\ivanry\PycharmProjects\ga_test\venv\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


ValueError: Expected 2D array, got 1D array instead:
array=[1.         0.         0.         0.         0.         0.63157895
 0.         0.         0.33333333 0.         0.5        0.75
 0.         0.         0.5        0.5        1.         0.
 1.         0.66666667 0.         0.18       0.         0.
 0.         0.2687813  0.2826087  0.66666667 0.40740741 0.10195228
 0.28077092 0.23333333 0.05328577 0.21330472 0.11515152 0.47381099
 0.12639405 0.79400749 0.20235078 0.         1.         0.
 0.06867554 0.26089627 0.375      0.37100737].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [10]:
np.random.randint(2, size=[5, 100])

array([[0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
        1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0,
        0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0,
        0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
        1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
        0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1,
        0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1,
        0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0,
        0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1,
        1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1,
        0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1,
        0, 1, 1, 1, 1,